const TOURNAMENT = {
  teams: [
    { name: "Kansas" },
    { name: "Austin Peay" },
    { name: "Colorado" },
    { name: "UConn" },
    { name: "Maryland" },
    { name: "South Dakota St" },
    { name: "Cal" },
    { name: "Hawaii" },
    { name: "Arizona" },
    { name: "Wichita St" },
    { name: "Miami" },
    { name: "Buffalo" },
    { name: "Iowa" },
    { name: "Temple" },
    { name: "Villanova" },
    { name: "UNC Asheville" },

    { name: "Oregon" },
    { name: "Holy Cross" },
    { name: "Saint Joe's" },
    { name: "Cincinnati" },
    { name: "Yale" },
    { name: "Baylor" },
    { name: "UNC Wilmington" },
    { name: "Duke" },
    { name: "Texas" },
    { name: "Northern Iowa" },
    { name: "Texas A&M" },
    { name: "Green Bay" },
    { name: "Oregon State" },
    { name: "VCU" },
    { name: "Oklahoma" },
    { name: "CSU Bakersfield" },

    { name: "UNC" },
    { name: "FGCU" },
    { name: "USC" },
    { name: "Providence" },
    { name: "Chattanooga" },
    { name: "Indiana" },
    { name: "Stony Brook" },
    { name: "Kentucky" },
    { name: "Notre Dame" },
    { name: "Michigan" },
    { name: "West Virginia" },
    { name: "SF Austin" },
    { name: "Wisconsin" },
    { name: "Pitt" },
    { name: "Xavier" },
    { name: "Weber State" },

    { name: "UVA" },
    { name: "Hampton" },
    { name: "Texas Tech" },
    { name: "Butler" },
    { name: "Purdue" },
    { name: "AR-Little Rock" },
    { name: "Iowa State" },
    { name: "Iona" },
    { name: "Seton Hall" },
    { name: "Gonzaga" },
    { name: "Utah" },
    { name: "Fresno State" },
    { name: "Dayton" },
    { name: "Syracuse" },
    { name: "Michigan State" },
    { name: "Mid Tennessee" },
  ],
  regions: [
    "South",
    "West",
    "East",
    "Midwest"
  ]
};

export default TOURNAMENT;
